/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Ted' at '17-10-21 上午1:36' with Gradle 2.9
 *
 * @author Ted, @date 17-10-21 上午1:36
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
